### ISSUE TITLE
Support Refile attachments

### ISSUE THREAD

**Issue by erickguan** [DHUers/RigidJudge#5]
文件地址是 `/store/:file_id:/:file_name`。

例子，对于 `input_file`：`/store/8cf8955ef6125031b4b1af08c1155fc88bbfc7c530725ef780972a642133/input_file`。

`file_id`: `8cf8955ef6125031b4b1af08c1155fc88bbfc7c530725ef780972a642133`
`file_name`: `input_file`
store 是 backend，看文件存的位置，这个是本地。

将 `/store/8cf8955ef6125031b4b1af08c1155fc88bbfc7c530725ef780972a642133/input_file` 扔到 `OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new("sha1"), secret_key, path)`。
secret_key 定义在 `RIGIDOJ_REFILE_TOKEN`。得到的 token 组成链接。
`/attachments/:token/store/8cf8955ef6125031b4b1af08c1155fc88bbfc7c530725ef780972a642133/input_file`

你想得到什么呢？

**Comment by wujysh** [comment]
finished
